{% set name = "verta" %}
{% set version = "0.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b54d54a5aa2f9263b4bf7b20889856e81a3dd576d7be56d7f713c16f47b6a276

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - click >=7.0,<9.0
    - cloudpickle >=1.0,<3.0
    - googleapis-common-protos >=1.5,<2.0
    - importlib-metadata >=3.7.0
    - protobuf >=3.8,<4.0
    - pytimeparse >=1.1.8,<2.0
    - pyyaml >=5.1,<7.0
    - requests >=2.25,<3.0
    - urllib3 >=1.26.0

test:
  imports:
    - verta

about:
  home: https://verta.readthedocs.io/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python client for interfacing with ModelDB

  doc_url: https://verta.readthedocs.io/
  dev_url: https://github.com/VertaAI/modeldb/tree/master/client/verta

extra:
  recipe-maintainers:
    - liuverta
    - ewagner-verta
