{% set name = "verta" %}
{% set version = "0.20.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6db164d1c89026d85bd5b6026ec7760df7ea2d4c2a8135399af8234e65139509

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python =2.7|>=3.5
    - pip
  run:
    - python =2.7|>=3.5
    - click >=7.0,<9.0
    - cloudpickle ~=1.0
    - googleapis-common-protos >=1.5,<2.0
    - pathlib2 >=2.2,<3.0
    - protobuf >=3.8,<3.18
    - pytimeparse >=1.1.8,<2.0
    - pyyaml >=5.1,<6.0
    - requests >=2.21,<3.0

test:
  imports:
    - verta

about:
  home: https://verta.readthedocs.io/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python client for interfacing with ModelDB

  doc_url: https://verta.readthedocs.io/
  dev_url: https://github.com/VertaAI/modeldb/tree/master/client/verta

extra:
  recipe-maintainers:
    - liuverta
    - mvartakAtVerta
