{% set name = "verta" %}
{% set version = "0.14.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1e436cc88617622d9343f5dd7534bd09806c0a9e9c3b1e25ea8e79477b89d612

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click
    - cloudpickle
    - googleapis-common-protos >=1.5
    - pathlib2 >=2.2
    - protobuf >=3.8
    - pyyaml >=5.1
    - requests >=2.21,<3.0

test:
  imports:
    - verta

about:
  home: https://verta.readthedocs.io/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python client for interfacing with ModelDB

  doc_url: https://verta.readthedocs.io/
  dev_url: https://github.com/VertaAI/modeldb/tree/master/client/verta

extra:
  recipe-maintainers:
    - convoliution
    - mvartakAtVerta
