{% set name = "verta" %}
{% set version = "0.18.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0c63f7f29e7d5a964efc49b2beec0342b9fd10564efaf64ce327482474c1abc8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python =2.7|>=3.5
    - pip
  run:
    - python =2.7|>=3.5
    - click ~=7.0
    - cloudpickle ~=1.0
    - googleapis-common-protos >=1.5,<2.0
    - pathlib2 >=2.2,<3.0
    - protobuf >=3.8,<4.0
    - pytimeparse >=1.1.8,<2.0
    - pyyaml >=5.1,<5.4
    - requests >=2.21,<3.0

test:
  imports:
    - verta

about:
  home: https://verta.readthedocs.io/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python client for interfacing with ModelDB

  doc_url: https://verta.readthedocs.io/
  dev_url: https://github.com/VertaAI/modeldb/tree/master/client/verta

extra:
  recipe-maintainers:
    - convoliution
    - mvartakAtVerta
