{% set name = "verta" %}
{% set version = "0.17.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 099bb3225dba216114ede843c78608c1c34e6fdd47b953ac5757d1c43687d0db

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python =2.7|>=3.5
    - pip
  run:
    - python =2.7|>=3.5
    - click
    - cloudpickle
    - googleapis-common-protos >=1.5
    - pathlib2 >=2.2
    - protobuf >=3.8
    - pyyaml >=5.1,<5.4
    - requests >=2.21,<3.0

test:
  imports:
    - verta

about:
  home: https://verta.readthedocs.io/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python client for interfacing with ModelDB

  doc_url: https://verta.readthedocs.io/
  dev_url: https://github.com/VertaAI/modeldb/tree/master/client/verta

extra:
  recipe-maintainers:
    - convoliution
    - mvartakAtVerta
