{% set name = "verta" %}
{% set version = "0.16.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5ade33c1739e701eaa3207bd92a4de78b8d5b004a52990c5ddd0913a60f5d8c4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click
    - cloudpickle
    - googleapis-common-protos >=1.5
    - pathlib2 >=2.2
    - protobuf >=3.8
    - pyyaml >=5.1
    - requests >=2.21,<3.0

test:
  imports:
    - verta

about:
  home: https://verta.readthedocs.io/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python client for interfacing with ModelDB

  doc_url: https://verta.readthedocs.io/
  dev_url: https://github.com/VertaAI/modeldb/tree/master/client/verta

extra:
  recipe-maintainers:
    - convoliution
    - mvartakAtVerta
