{% set name = "verta" %}
{% set version = "0.16.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e5acb5410dc88db57a89c9078cbef9711136fab032da87a05de272b9dfd5f59a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click
    - cloudpickle
    - googleapis-common-protos >=1.5
    - pathlib2 >=2.2
    - protobuf >=3.8
    - pyyaml >=5.1
    - requests >=2.21,<3.0

test:
  imports:
    - verta

about:
  home: https://verta.readthedocs.io/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python client for interfacing with ModelDB

  doc_url: https://verta.readthedocs.io/
  dev_url: https://github.com/VertaAI/modeldb/tree/master/client/verta

extra:
  recipe-maintainers:
    - convoliution
    - mvartakAtVerta
