{% set name = "verta" %}
{% set version = "0.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4c12bc765e7eb978476f179fa53e3004d901f6a9afa517d3de7a6d8814b79867

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - googleapis-common-protos >=1.5
    - grpcio >=1.16
    - joblib >=0.13
    - protobuf >=3.6
    - requests >=2.21

test:
  imports:
    - verta

about:
  home: https://verta.readthedocs.io/en/latest/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python client for interfacing with ModelDB'

  doc_url: https://verta.readthedocs.io/en/latest/
  dev_url: https://github.com/VertaAI/modeldb-client/

extra:
  recipe-maintainers:
    - convoliution
    - mvartakAtVerta
