{% set name = "verta" %}
{% set version = "0.13.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d11419e48c7aa433be799a2133bfde64484120a6cc33c76c4360f4a2df30cba0

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - cloudpickle
    - googleapis-common-protos >=1.5
    - grpcio >=1.16
    - pathlib2 >=2.1
    - protobuf >=3.6
    - requests >=2.21
    - six >=1.12

test:
  imports:
    - verta

about:
  home: https://verta.readthedocs.io/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python client for interfacing with ModelDB'

  doc_url: https://verta.readthedocs.io/
  dev_url: https://github.com/VertaAI/modeldb-client/

extra:
  recipe-maintainers:
    - convoliution
    - mvartakAtVerta
