{% set name = "verta" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fc67d92bac4b257169cb0f5e8521e255d23dd2a35ff1eb09f11268e20ded9935

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - googleapis-common-protos >=1.5
    - grpcio >=1.16
    - joblib >=0.13
    - pathlib2 >=2.1
    - protobuf >=3.6
    - requests >=2.21

test:
  imports:
    - verta

about:
  home: https://verta.readthedocs.io/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python client for interfacing with ModelDB'

  doc_url: https://verta.readthedocs.io/
  dev_url: https://github.com/VertaAI/modeldb-client/

extra:
  recipe-maintainers:
    - convoliution
    - mvartakAtVerta
