travis:
  secure:
    BINSTAR_TOKEN: jeIBonfk7OMNRKVx2cMMZkUi3yNuve7+9tGYZKvP8swprsJB2KimfGXndlAqzXFDBbdJaWsNm6pfleINvaOFjuAXKWK3KUkL3mUN3OSDZ7g1kbWrgKcjmlWVSJijvYAoOJkWyqEgAYQj53+97c4PrbtSz8x0yPXy+7PslcSlz9VJSr6uMa1gU6kZf9/6PZ1S815XCmcmIq2Ds5hriBdA2eskfTfhYm9as2wdC3mIWdEuG64/1h9r/JxocmH6lObxNAhP+ew7ywbQgRMApS44gaDiZz4fI72GhDy1zfqP/p23TbNAs/ZOt+YjDHHCmvGiriXYgk0mnaPxm/H6r+dQSgG7u2TNtaODYNmoWeIEsOBadA/l4Q+b1Hg5AZiyyRcfndsdxDuhnWLPExjj+WpFd6LIphQv1lCwgYqz1T+dw8j/RBpYANSvYm7OVIq8B5rSWFATEJxg5Hadss4OffJb+4XnSyFbMOfkXuYtMhSDHTGhYhLkJ36Gwbz2WdANEHyJBdYcpPDV9bAGMO3YixTfmqlXJCyrU/xWBle+rfvPyGBmbLLSMiP/Ey+/X3rJnqsxgDIWK9jGGvbC88lflNC7zcTYWtfw796/W9LdF6V39lG7KTkvGhyAJKH3f4yn5fQlPOjOCFBStDsgaLLVxbkfjhe+Jly3l1gtDQvJ5zNsxyc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
